### ISSUE TITLE
Perhaps a problem running v5.0.0 alpha 2021-05-06 on some machines?

### ISSUE THREAD

**Issue by niksedk** [UB-Mannheim/tesseract#47]
thx for the new alpha version :)

It runs fine for me... but some users seem to have problems with some (missing?) dll files, `libgcc_s_dw2-1.dll` and `libgcc_s_sjlj-1.dll`:
https://github.com/SubtitleEdit/subtitleedit/issues/5029#issuecomment-838853397

Any ideas?

**Comment by stweil** [comment]
Yes, sorry, the 32 bit installer was incomplete. This was caused by a Debian cross compiler update which no longer includes that DLL file.

I replaced the faulty installer by a new one with the same name and content, but added the two missing DLL files.

Please test it and close the issue if it works for you.

**Comment by niksedk** [comment]
Thx Stefan, works great now :)
