### ISSUE TITLE
VirusTotal detection for Windows installer [Security Issue]

### ISSUE THREAD

**Issue by fatihkaymak** [UB-Mannheim/tesseract#55]
I have downloaded the installer 64 bit EXE for Windows. Then over VirusTotal.com we scanned the EXE. As result; we saw that there is a TROJAN issue: "Antiy-AVL >> Trojan/Generic.ASMalwS.34D3112"
because of this is a trojan warning; we could not proceed with the installer. 

https://www.virustotal.com/gui/file/30b6f129532003a1b73953056fb49dc1cc9d993f819834038bf953d7e79186bd/detection

Please fix this issue or could you give further info about that if it was not real issue? This info should be acceptable for our security team. 

Best regards.

**Comment by stweil** [comment]
This happens from time to time. See old issues #18 and #19 for the explanation.

**Comment by stweil** [comment]
Tesseract is cross built on a Debian GNU Linux server and uses the NSIS installer to build the Windows installer executables. As far as I know the NSIS components sometimes trigger a (false) virus alarm, maybe because some virus executables also use NSIS (but that is my personal speculation). We now had no such alarms for more than two years, and now there is this new company which thinks that there is a virus.

If you are in doubt, you can build your own Tesseract installers. All code is available, see for example the CI build https://github.com/UB-Mannheim/tesseract/actions/runs/1667636408. The 64 bit installer which was produced by GitHub actions also triggers the same alarm: https://www.virustotal.com/gui/file-analysis/YmI4NTVjZmNjM2Y3YzFhMjhkYTY2YWI2NGViODllYTE6MTY0Mjc4NjAwMw==.
