### ISSUE TITLE
Outdated Leptonica version

### ISSUE THREAD

**Issue by amitdo** [UB-Mannheim/tesseract#67]
It seems you ship Leptonica 1.78 with Tesseract 5.3.0.

If that's indeed true, please upgrade to 1.83.

Thanks.

**Comment by stweil** [comment]
The Tesseract installer for Windows is built using the latest msys packages.

**Comment by amitdo** [comment]
://github.com/tesseract-ocr/tesseract/issues/4031#issuecomment-1474842219

https://github.com/tesseract-ocr/tesseract/issues/4029

https://packages.msys2.org/package/mingw-w64-i686-leptonica

https://packages.msys2.org/package/mingw-w64-x86_64-leptonica

**Comment by amitdo** [comment]
How do you explain the fact that we got reports from people that downloaded your installer and now have Tesseract 5.3.0 and Leptonica 1.78 according to 'tesseract -v'?

**Comment by stweil** [comment]
I had to look that up myself because I had forgotton the details of the build process from December.

> The Tesseract installer for Windows is built using the latest msys packages.

That's not the full truth. I planned to do so, but had little time when building in December and decided to use the old build environment which uses outdated packages from Cygwin and an old self-compiled package for Leptonica.

So the correct statement should be: The next Tesseract installer for Windows will be built using the latest msys packages.

**Comment by amitdo** [comment]
Yes, you have `liblept-5.dll` while msys5 has `libleptonica-6.dll`.

**Comment by stweil** [comment]
I just finished a [new installer for Tesseract 5.3.1](https://github.com/UB-Mannheim/tesseract/wiki/) which is now using recent packages for all dependencies.
